# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Actiontest < Formula
  desc ""
  homepage "https://github.com/tcotav/actiontest"
  version "1.0.2"

  on_macos do
    url "https://github.com/tcotav/actiontest/releases/download/v1.0.2/actiontest_1.0.2_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "3fd37bd127745510e32c0d56648e8cf25e80902ebf723f7050a96ba00981cf81"

    def install
      bin.install "actiontest"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcotav/actiontest/releases/download/v1.0.2/actiontest_1.0.2_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ff558bd31e2b024160db465b0f7ba4c77038a61004680dd94eb0650910a447ff"

      def install
        bin.install "actiontest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tcotav/actiontest/releases/download/v1.0.2/actiontest_1.0.2_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0a1fe63e97b6b6cd74fe11783482718a3482728e2ec612da94c6cc1126716fdb"

      def install
        bin.install "actiontest"
      end
    end
  end
end
