# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Actiontest < Formula
  desc ""
  homepage "https://github.com/tcotav/actiontest"
  version "1.0.0"

  on_macos do
    url "https://github.com/tcotav/actiontest/releases/download/v1.0.0/actiontest_1.0.0_darwin_all.tar.gz"
    sha256 "86e450d97a68b00695f07b8e45d98dc912bd3758e9a5edea6dc92dd150a0a9e2"

    def install
      bin.install "actiontest"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tcotav/actiontest/releases/download/v1.0.0/actiontest_1.0.0_linux_amd64.tar.gz"
      sha256 "c4dc18a8bef77847678f8762dd991a2966453daba6a5138b13d5a52466919a5c"

      def install
        bin.install "actiontest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcotav/actiontest/releases/download/v1.0.0/actiontest_1.0.0_linux_arm64.tar.gz"
      sha256 "3c0448bdf81717be5693cf07455fb92328b1f7abc990ee5ed2a4b7835fe22faa"

      def install
        bin.install "actiontest"
      end
    end
  end
end
