# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Actiontest < Formula
  desc ""
  homepage "https://github.com/tcotav/actiontest"
  version "1.0.5"

  on_macos do
    url "https://github.com/tcotav/actiontest/releases/download/v1.0.5/actiontest_1.0.5_darwin_all.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
    sha256 "1b98cbf3bb37e37fe87e799a73bfe9c7cd211436dbfad322a20ccf73b66436b1"

    def install
      bin.install "actiontest"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tcotav/actiontest/releases/download/v1.0.5/actiontest_1.0.5_linux_amd64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
      sha256 "75315641c2f705078b08a63b82b3f87c952988e6dd1010691326411e470b2c32"

      def install
        bin.install "actiontest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcotav/actiontest/releases/download/v1.0.5/actiontest_1.0.5_linux_arm64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
      sha256 "5c1d7147bcddd15769ac27a17d80477537fee1774efcb4649adbafef7bf83dbf"

      def install
        bin.install "actiontest"
      end
    end
  end
end
